platform :ios, '8.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'ChatDemo-UI3.0' do

	pod 'Hyphenate'

	pod 'EaseUI', :git => 'https://lizilong1989@github.com/lizilong1989/easeui-ios-hyphenate-cocoapods.git', :branch => '3party_easeui'

	pod 'RedpacketAliAuthLib', '~> 1.1.4'

	pod 'MBProgressHUD', '~> 1.0.0'

end

target 'ChatDemo-UI3.0-JDPay' do
    
	pod 'Hyphenate'

	pod 'EaseUI', :git => 'https://lizilong1989@github.com/lizilong1989/easeui-ios-hyphenate-cocoapods.git', :branch => '3party_easeui'
    
    	pod 'RedpacketLib'

end
